#ifndef TOKEN_H
#define TOKEN_H

typedef enum {
     TOKEN_EOF=0,
	 TOKEN_IDENT,
	 TOKEN_T_ARRAY,
	 TOKEN_T_AUTO,
	 TOKEN_T_BOOLEAN,
	 TOKEN_T_CHAR,
	 TOKEN_ELSE,
	 TOKEN_FALSE,
	 TOKEN_FOR,
	 TOKEN_FUNCTION,
	 TOKEN_IF,
	 TOKEN_T_INTEGER,
	 TOKEN_PRINT,
	 TOKEN_RETURN,
	 TOKEN_T_STRING,
	 TOKEN_TRUE,
	 TOKEN_VOID,
	 TOKEN_WHILE,
     TOKEN_INCREMENT,
     TOKEN_ADD,
     TOKEN_ERROR
} token_t;

#endif
